"""
Skill: moderate_comments

Reviews the full set of stored comments for one PR review together (not
one at a time) so it can actually spot duplicates across agents. Returns
a verdict per comment: approve or reject, never an edit.
"""

import json
from typing import Any, Dict, List

from langchain_core.prompts import ChatPromptTemplate

from src.llm_config import get_llm

SYSTEM_PROMPT = """You are moderating code review comments before they are \
posted to a pull request. You will receive a list of comments generated by \
different reviewer agents (correctness, security, style).

For each comment, decide:
- Reject it if it duplicates another comment in the list (same underlying \
issue, possibly worded differently, possibly flagged by two agents) — keep \
one, reject the rest.
- Reject it if it is vague, generic, or not actionable (e.g. "consider \
improving error handling" with no specifics).
- Approve it otherwise.

Do NOT edit or rewrite any comment. Only approve or reject.

Return ONLY a JSON array, no other text, in exactly this form:
[{{"id": <comment id as integer>, "status": "approved" | "rejected", "notes": "<one short sentence>"}}]
"""

_prompt = ChatPromptTemplate.from_messages(
    [("system", SYSTEM_PROMPT), ("human", "Comments:\n{comments_block}")]
)

_chain = _prompt | get_llm(max_tokens=1200)


def moderate_comments(comments: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    if not comments:
        return []

    comments_block = "\n".join(
        f"id={c['id']} [{c['agent_name']}]: {c['comment']}" for c in comments
    )
    response = _chain.invoke({"comments_block": comments_block})
    raw = response.content.strip()

    if raw.startswith("```"):
        raw = raw.strip("`")
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    parsed = json.loads(raw)

    # Only ever carry forward id/status/notes — even if the model ignores
    # instructions and returns a "comment" field, it's dropped here before
    # it reaches the DB layer.
    verdicts = [
        {"id": v["id"], "status": v["status"], "notes": v.get("notes", "")}
        for v in parsed
    ]

    returned_ids = {v["id"] for v in verdicts}
    for c in comments:
        if c["id"] not in returned_ids:
            verdicts.append(
                {"id": c["id"], "status": "rejected", "notes": "no verdict returned by moderator"}
            )
    return verdicts